[package]
name = "hypr-panel"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
gtk = "0.18.2"
gtk-layer-shell = "0.8.2"
serde = "1.0.228"
serde_json = "1.0.149"
sysinfo = "0.38.1"
tokio = "1.49.0"
