[package]
name = "hypr-panel"
version = "0.1.0"
edition = "2024"

[dependencies]
async-channel = "2.5.0"
cairo-rs = "0.21.5"
chrono = "0.4.43"
gtk4 = "0.10.3"
gtk4-layer-shell = "0.7.1"
libc = "0.2.182"
pango = "0.21.5"
pangocairo = "0.21.5"
serde_json = "1.0.149"
udev = "0.9.3"
