[package]
name = "hypr-panel"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.43"
gtk4 = "0.10.3"
gtk4-layer-shell = "0.7.1"
serde = "1.0.228"
serde_json = "1.0.149"
sysinfo = "0.38.1"
tokio = "1.49.0"
